// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hosts.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Parameters    string                 `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_hosts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Payload) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *Payload               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_hosts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_hosts_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobReply) Reset() {
	*x = JobReply{}
	mi := &file_hosts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReply) ProtoMessage() {}

func (x *JobReply) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReply.ProtoReflect.Descriptor instead.
func (*JobReply) Descriptor() ([]byte, []int) {
	return file_hosts_proto_rawDescGZIP(), []int{2}
}

func (x *JobReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hosts_proto protoreflect.FileDescriptor

const file_hosts_proto_rawDesc = "" +
	"\n" +
	"\vhosts.proto\x12\x05hosts\"=\n" +
	"\aPayload\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tR\n" +
	"parameters\"F\n" +
	"\n" +
	"JobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\apayload\x18\x02 \x01(\v2\x0e.hosts.PayloadR\apayload\"$\n" +
	"\bJobReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2=\n" +
	"\n" +
	"JobService\x12/\n" +
	"\aSendJob\x12\x11.hosts.JobRequest\x1a\x0f.hosts.JobReply\"\x00B4Z2github.com/giulian-coding/hosts/internal/grpc;grpcb\x06proto3"

var (
	file_hosts_proto_rawDescOnce sync.Once
	file_hosts_proto_rawDescData []byte
)

func file_hosts_proto_rawDescGZIP() []byte {
	file_hosts_proto_rawDescOnce.Do(func() {
		file_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hosts_proto_rawDesc), len(file_hosts_proto_rawDesc)))
	})
	return file_hosts_proto_rawDescData
}

var file_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hosts_proto_goTypes = []any{
	(*Payload)(nil),    // 0: hosts.Payload
	(*JobRequest)(nil), // 1: hosts.JobRequest
	(*JobReply)(nil),   // 2: hosts.JobReply
}
var file_hosts_proto_depIdxs = []int32{
	0, // 0: hosts.JobRequest.payload:type_name -> hosts.Payload
	1, // 1: hosts.JobService.SendJob:input_type -> hosts.JobRequest
	2, // 2: hosts.JobService.SendJob:output_type -> hosts.JobReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hosts_proto_init() }
func file_hosts_proto_init() {
	if File_hosts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hosts_proto_rawDesc), len(file_hosts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hosts_proto_goTypes,
		DependencyIndexes: file_hosts_proto_depIdxs,
		MessageInfos:      file_hosts_proto_msgTypes,
	}.Build()
	File_hosts_proto = out.File
	file_hosts_proto_goTypes = nil
	file_hosts_proto_depIdxs = nil
}
